### ISSUE TITLE
为什么我的 presenter 是空的

### ISSUE THREAD

**Issue by William-Chow** [JessYanCoding/MVPArt#11]
@Override
    public void initData(@Nullable Bundle savedInstanceState) {
          **mPresenter.requestGetToken(Message.obtain(MainActivity.this, new Object[]{true}));**
    }

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.art.client.android/com.art.client.android.mvp.ui.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.art.client.android.mvp.presenter.MainPresenter.requestGetToken(me.jessyan.art.mvp.Message)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.art.client.android.mvp.presenter.MainPresenter.requestGetToken(me.jessyan.art.mvp.Message)' on a null object reference
        at com.art.client.android.mvp.ui.activity.MainActivity.initData(MainActivity.java:27)
        at me.jessyan.art.base.BaseActivity.onCreate(BaseActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)

**Comment by William-Chow** [comment]
没事，我发现是我自己的问题
